//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizApp
{


    public partial class WebForm1
    {

        /// <summary>
        /// ScriptManager1 control.
        /// </summary>
        protected global::System.Web.UI.ScriptManager ScriptManager1;

        /// <summary>
        /// upMain control.
        /// </summary>
        protected global::System.Web.UI.UpdatePanel upMain;

        /// <summary>
        /// pnlSetup control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlSetup;

        /// <summary>
        /// txtUserName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtUserName;

        /// <summary>
        /// rfvUserName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvUserName;

        /// <summary>
        /// rblCategory control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RadioButtonList rblCategory;

        /// <summary>
        /// rfvCategory control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvCategory;

        /// <summary>
        /// chkTimer control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CheckBox chkTimer;

        /// <summary>
        /// btnStart control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnStart;

        /// <summary>
        /// pnlQuiz control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlQuiz;

        /// <summary>
        /// lblUserGreeting control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblUserGreeting;

        /// <summary>
        /// progressBarFill control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel progressBarFill;

        /// <summary>
        /// lblQuestionNumber control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblQuestionNumber;

        /// <summary>
        /// pnlTimer control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlTimer;

        /// <summary>
        /// lblTimer control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTimer;

        /// <summary>
        /// lblQuestion control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblQuestion;

        /// <summary>
        /// rblOptions control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RadioButtonList rblOptions;

        /// <summary>
        /// rfvOptions control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvOptions;

        /// <summary>
        /// btnNext control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnNext;

        /// <summary>
        /// quizTimer control.
        /// </summary>
        protected global::System.Web.UI.Timer quizTimer;

        /// <summary>
        /// pnlResult control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlResult;

        /// <summary>
        /// lblResultGreeting control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblResultGreeting;

        /// <summary>
        /// lblScore control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblScore;

        /// <summary>
        /// lblRemark control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblRemark;

        /// <summary>
        /// rptReview control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptReview;

        /// <summary>
        /// btnRestart control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnRestart;
    }
}
